spring:
  application:
    name: Property Management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp-mail.outlook.com
    port: 25
    username: "email"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082

